draft-pauly-connect-quic.md

Explanatory text to explain goals and limitations

Explain guarantees provided by CONNECT-QUIC

---

draft-pauly-connect-quic.md

Define proxy mapping state more rigorously

---

draft-pauly-masque-quic-proxy.md

This PR is mostly editorial, but it also adds a little text to close Lucas' two issues.
Closes #26, closes #27.

Various cleanups

---

draft-pauly-masque-quic-proxy.md

Mention connection migration

---

draft-pauly-masque-quic-proxy.md

Describe conflicts with no connection IDs

---

draft-pauly-masque-quic-proxy.md

Restrictions on use of server-facing socket

---

draft-pauly-masque-quic-proxy.md

Add packet size considerations

---

draft-pauly-masque-quic-proxy.md

Suggestions from Eric Rosenberg

Clarify mapping language

---

draft-pauly-masque-quic-proxy.md

bidirectional virtual connection ids

---

draft-pauly-masque-quic-proxy.md

Unify around "forwarded mode"

---

draft-pauly-masque-quic-proxy.md

allow clients to send capsules before HTTP response

---

draft-pauly-masque-quic-proxy.md

Explain ECN handling in forwarded mode

---

draft-pauly-masque-quic-proxy.md

Mention using PINGs to keep tunnels alive

---

draft-pauly-masque-quic-proxy.md

add forwarded mode packets to example

---

draft-ietf-masque-quic-proxy.md

Handle versioning of scramble

---

draft-ietf-masque-quic-proxy.md

draft text for security considerations

---

draft-ietf-masque-quic-proxy.md

null -> identity

---

draft-ietf-masque-quic-proxy.md

Fix capsule registration

---

draft-ietf-masque-quic-proxy.md

Expand on active attack differences

---

draft-ietf-masque-quic-proxy.md

Require client VCID to be at least as long as real client CID 

---

draft-ietf-masque-quic-proxy.md

MAX_CONNECTION_IDS capsule

---

draft-ietf-masque-quic-proxy.md

guidance for disabling forwarding mode

---

draft-ietf-masque-quic-proxy.md

Addresses #84. Depends on #120

Port sharing guidance

---

draft-ietf-masque-quic-proxy.md

change guidance introduced in #126

define proper use of transform parameters

---

draft-ietf-masque-quic-proxy.md

Add section explaining server preferred addresses

---

draft-ietf-masque-quic-proxy.md

Don't allow VCID == CID

---

draft-ietf-masque-quic-proxy.md

Fix identity transform title

---

draft-ietf-masque-quic-proxy.md

highlight how registration does not introduce delays

---

draft-ietf-masque-quic-proxy.md

mention that forwarded mode isnt always better
